packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': false
  '@prisma/engines': false
  '@sentry/cli': false
  argon2: false
  esbuild: false
  msgpackr-extract: true
  prisma: false
  sharp: false
  unrs-resolver: false
